#!/bin/bash

# DEPRECATED: See the vibe coded in src/cli.js for the new CLI implementation. 
# This file is still here for reference.


INVRT_DIRECTORY=$INIT_CWD"/invrt"
echo "📁 INVRT_DIRECTORY: $INVRT_DIRECTORY"

# Read the config for the current project
CONFIG_FILE="$INVRT_DIRECTORY/config.yaml"
INVRT_URL=$(yq e '.project.url' $CONFIG_FILE);
INVRT_DEPTH_TO_CRAWL=$(yq e '.settings.max_crawl_depth' $CONFIG_FILE);
INVRT_MAX_PAGES=$(yq e '.settings.max_pages' $CONFIG_FILE);
INVRT_USER_AGENT=$(yq e '.settings.user_agent' $CONFIG_FILE);
INVRT_MAX_CONCURRENT_REQUESTS=$(yq e '.settings.max_concurrent_requests' $CONFIG_FILE);
INVRT_CRAWL_OUTPUT_DIR="$INVRT_DIRECTORY/data/crawled_urls.txt"
INVRT_CRAWL_LOG_DIR="$INVRT_DIRECTORY/data/logs/crawl.log"
INVRT_CRAWL_ERROR_LOG_DIR="$INVRT_DIRECTORY/data/logs/crawl_error.log"

INVRT_PROFILE='default';
INVRT_DEVICE='desktop';

INVRT_DIRECTORY=$PWD."/invrt"



scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
case "$1" in
    "init")
        source "$scripts/invrt-init.sh"
        ;;
    "crawl")
        source "$scripts/invrt-crawl.sh"
        ;;
    "reference")
        source "$scripts/invrt-reference.sh"
        ;;
    "test")
        source "$scripts/invrt-test.sh"
        ;;
    *)
        echo "Invalid command. Usage: $0 {init|crawl|reference|test}"
        exit 1
        ;;
esac